lab10/webServer/webApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'webApp'
urlpatterns = [
	url(r'login/', views.login, name='login'),
	url(r'logout/', views.logout, name='logout'),
    url(r'signup/', views.signup, name='signup'),

    url(r'settings/', views.settings, name='settings'),
    url(r'home/', views.home, name='home'),

    url(r'courses/', views.courses, name='courses'),
	url(r'deadlines/', views.deadlines, name='deadlines'),
    url(r'feedback/', views.feedback, name='feedback'),
    url(r'coursesnew/', views.coursesnew, name='coursesnew'),
	url(r'deadlinesnew/', views.deadlinesnew, name='deadlinesnew'),
	url(r'feedbacknew/', views.feedbacknew, name='feedbacknew'),
    url(r'studentInitialise/', views.studentInitialise, name='studentInitialise'),


    url(r'api/', views.android_data, name='andy'),

]

lab10/webServer/webServer/urls.py
from django.conf.urls import include, url
from django.contrib import admin
urlpatterns = [
	url(r'^webApp/', include('webApp.urls')),
    url(r'^admin/', admin.site.urls),
]

lab10/webServer/webApp/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from datetime import date
from datetime import time
import calendar

MaxNameLength = 30;

default_deadlines = {
    'Spring':[date.today().replace(day=28, month=2) ,date.today().replace(day=15, month=4) ],
    'Summer':[date.today().replace(day=1, month=6) ,date.today().replace(day=15, month=7)],
    'Autumn':[date.today().replace(day=6, month=9) ,date.today().replace(day=18, month=11)]
    }

class Professor(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return "%s: %s %s" %(self.usernameer.username, self.user.first_name, self.user.last_name)

class Student(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rollno = models.CharField(max_length = 15, primary_key=True)
    token = models.CharField(max_length = 64, default="0")

    def __str__(self):
        return "%s: %s %s" %(self.rollno,self.user.first_name, self.user.last_name)

    class Meta:
        ordering = ('rollno',)

class Course(models.Model):

    code = models.CharField(max_length = 10, primary_key=True)
    name = models.CharField(max_length = 50)
    period = models.CharField(max_length = 20,default='Summer')
    year = models.CharField(max_length = 20,default='2016')

    professor = models.ForeignKey(Professor)
    students = models.ManyToManyField(Student)

    def __str__(self):
        return "%s: %s" %(self.code, self.name)

    class Meta:
        ordering = ('code','name')

class Deadline(models.Model):

    date = models.DateField()
    time = models.TimeField()
    course = models.ForeignKey(Course)
    description = models.TextField(max_length=50)

    def __str__(self):
        return "%s" %(self.description)


class FeedbackForm(models.Model):
    deadline = models.ForeignKey(Deadline)

class Question(models.Model):
    description = models.TextField(max_length=200)
    feedbackForm = models.ForeignKey(FeedbackForm)

lab10/webServer/webApp/views.py
#for basic rendering of html pages
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect

#for authentication login and logout
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required

#models
from django.contrib.auth.models import User
from .models import *

#read student data
import csv
import json
#Logging in ang signing up
def login(request):
	if request.POST :
		user = authenticate(username=request.POST['name'], password=request.POST['pass'])
		if user is not None:
			if user.is_active:
				auth_login(request, user)
				return HttpResponseRedirect('/webApp/home/')
		return render(request, "webApp/login.html",context={'error':'invalid credentials'})
	else:
		if(request.user.is_authenticated):
			return HttpResponseRedirect('/webApp/home/')
		else:
			return render(request, "webApp/login.html",context={'error':''})

def signup(request):
	if request.POST :
		x= User.objects.create_user(request.POST['name'],
			request.POST['email'], request.POST['pass'])
		x.save();
		auth_login(request,x)
		return HttpResponseRedirect('/webApp/home/')

	else:
		if(request.user.is_authenticated):
			return HttpResponseRedirect('/webApp/home/')
		else:
			return render(request, "webApp/signup.html")


#Home Page related in navigation bar
@login_required()
def home(request):
	return render(request, "webApp/home.html")

@login_required()
def logout(request):
	data={'name':request.user.username}
	auth_logout(request)
	return render(request, "webApp/logout.html",context=data)

@login_required()
def settings(request):
	if request.POST :
		u = User.objects.get(username__exact=request.user.username)
		if not u.check_password(request.POST['currPass']) :
			return render(request, "webApp/settings.html",context={'error':'Current Password Incorrect'})
		else:
			u.set_password(request.POST['newPass'])
		u.save()
		return HttpResponseRedirect('/webApp/logout/')
	else:
		return render(request, "webApp/settings.html",context={'error':''})


#Content pages
@login_required()
def courses(request):
	return render(request, "webApp/courses.html",context={'courses' : Course.objects.all()})

@login_required()
def coursesnew(request):
	if request.POST :
		if(len(Course.objects.filter(code=request.POST['code'])) != 0):
			data={
				'professors' : Professor.objects.all(),
				'students' : Student.objects.all(),
				'errors' : 'Course Already Exists'
			}
			return render(request, "webApp/coursesnew.html",context=data)

		profuser = User.objects.get(username=request.POST['professor'])
		prof = Professor.objects.get(user=profuser)

		c = prof.course_set.create(name=request.POST['name'],code=request.POST['code'],
			period=request.POST['group1'],year=request.POST['year'])
		c.save()



		d1 = Deadline(course=c,time=request.POST['time3'],description=request.POST['description3'],
			date=request.POST['date3'])
		d2 = Deadline(course=c,time=request.POST['time4'],description=request.POST['description4'],
			date=request.POST['date4'])
		d1.save()
		d2.save()


		deadl = c.deadline_set.create(time=request.POST['time2'],description=request.POST['description2'],
			date=request.POST['date2'])
		deadl.save()
		feedbck = deadl.feedbackform_set.create()
		feedbck.save()

		desc1 = "How good was teaching of instructor?"
		feedbck.question_set.create(description=desc1)
		desc2 = "Percentage of Classes you attended?"
		feedbck.question_set.create(description=desc2)

		deadl1 = c.deadline_set.create(time=request.POST['time1'],description=request.POST['description1'],
			date=request.POST['date1'])
		deadl1.save();

		feedbck1 = deadl1.feedbackform_set.create()
		feedbck1.save()

		desc3 = "How good was teaching of instructor?"
		feedbck1.question_set.create(description=desc3)
		desc4 = "Percentage of Classes you attended?"
		feedbck1.question_set.create(description=desc4)


		studusernames = request.POST.getlist('student')
		for i in range(len(studusernames)):
			studuser = User.objects.get(username=studusernames[i])
			stud = Student.objects.get(user=studuser)
			c.students.add(stud)

		return HttpResponseRedirect('/webApp/home/')
	else:
		data={
		'professors' : Professor.objects.all(),
		'students' : Student.objects.all(),
		'errors' : ''
		}
		return render(request, "webApp/coursesnew.html",context=data)

@login_required()
def deadlines(request):
	return render(request, "webApp/deadlines.html",context={'deadlines' : Deadline.objects.all()})

@login_required()
def deadlinesnew(request):
	if request.POST :
		corse = Course.objects.filter(code=request.POST['course'])
		deadl = corse[0].deadline_set.create(date=request.POST['date'],time=request.POST['time'],description=request.POST['description'])
		deadl.save()

		return HttpResponseRedirect('/webApp/home/')
	else:
		return render(request, "webApp/deadlinesnew.html",context={'courses' : Course.objects.all()})

@login_required()
def feedback(request):
	data={'forms' : [],
	'feedbacks' : []}
	x=FeedbackForm.objects.all()
	data['forms'] = FeedbackForm.objects.all();
	for i in range(len(x)):
		data[i] = Question.objects.filter(feedbackForm=x[i]);
	data['length'] =  len(x);
	return render(request, "webApp/feedback.html",context=data)


@login_required()
def feedbacknew(request):
	if request.POST :
		corse = Course.objects.filter(code=request.POST['course'])
		deadl = corse[0].deadline_set.create(date=request.POST['date'],time=request.POST['time'],description=request.POST['description'])
		deadl.save()
		feedbck = deadl.feedbackform_set.create()
		feedbck.save()
		noQ = int(request.POST['noQuestions'])
		for i in range(1,noQ+1):
			desc = request.POST['question'+str(i)]
			feedbck.question_set.create(description=desc)



		return HttpResponseRedirect('/webApp/home/')
	else:
		return render(request,  "webApp/feedbacknew.html",context={'courses' : Course.objects.all()})


@login_required()
def studentInitialise(request):
	if request.POST :

		myfile= request.FILES.get('students')
		with open('webApp/students.csv', 'wb+') as destination:
			for chunk in myfile.chunks():
				destination.write(chunk)

		with open('webApp/students.csv', 'rt') as f:
			reader = csv.reader(f)
			count=0

			for row in reader:
				count = count +1
				if count==1 :
					continue
				us = User.objects.filter(username=row[0])
				if len(us)!=0:
					us=us[0]
				else:
					us = User(username=row[0])
				us.first_name=row[3]
				us.last_name=row[4]
				us.is_staff = False
				us.set_password(row[1]);
				us.save()

				newst = Student(user=us,rollno=row[2])
				newst.save();

		return HttpResponseRedirect('/webApp/home/')
	else:
		return render(request,  "webApp/studentInitialise.html",context={'students' : Student.objects.all()})


# API service
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.middleware.csrf import get_token

@ensure_csrf_cookie
@csrf_exempt
def android_data(request):
	if request.method== 'POST':

		json_str=((request.body).decode('utf-8'))
		data = json.loads(json_str)
		user_name = data['username']
		pw = data['password']

		# user_name = request.POST['username']
		# pw = request.POST['password']

		usr = authenticate(username=user_name, password=pw)
		if usr is not None:
			if usr.is_active:
				s = Student.objects.filter(user=usr)
				if len(s) == 1 :
					s[0].token = get_token(request)
					auth_login(request,s[0].user);
					return JsonResponse(
						{
							'status':'yes',
							'csrftoken':request.COOKIES.get('csrftoken'),
							'sessionid':request.session.session_key
						}
						)
	return JsonResponse({'status':'no','csrftoken':request.COOKIES.get('csrftoken'), 'sessionid':request.session.session_key})

lab10/webServer/webApp/templates/webApp/bkbase.html
{% load staticfiles %}

<!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!-- Compiled and minified CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <!-- Compiled and minified JavaScript -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    </head>


    <body style="background: url({% static 'pictures/design_bg.png' %}) repeat fixed;">
      {% block main %}{% endblock %}
      {% block script %}{% endblock %}
    </body>
  </html>

lab10/webServer/webApp/templates/webApp/coursesnew.html
{% extends 'webApp/nav.html' %}
{% load staticfiles %}

{% block main1 %}
  <div>
    <div class="row" style="margin-top:2.5em">

      <div class = "col s0 m2">
      </div>

      <div class = "col s12 m8">
        <div class="card blue-white darken-1">
          <div class="card-content blue-text">
            <div class="row">
              <div class="card-title col m3 s0 center">
              </div>
            	<span class="card-title col m6 s12 center">
        				<nav style="margin-bottom: 30px;">
        				 	<div class="nav-wrapper" >
        						<ul class="center">
        				    		<li class="active col s12 m12 center">
        				    			<a href="#" style="font-size:1.1em">Add A Course</a>
        				    		</li>
        					  	</ul
        				  	</div>
        				</nav>
      		  	</span>
            </div>

            <div>
              <form class="form-horizontal" name="CourseForm" action="{% url 'webApp:coursesnew' %}" method="post"  autocomplete="off" onsubmit="return valid_date_all() ;">{% csrf_token %}

                <div class="form-group row">
                  <div class="input-field col s3 m3">
                    <input placeholder="eg. CS251" name="code" id="course_code" type="text" class="validate" required>
                    <label for="course_code">Course Code</label>
                  </div>
                  <div class="input-field col s9 m9">
                    <input placeholder="eg. Software Systems Lab" name="name" id="course_name" type="text" class="validate" required>
                    <label for="last_name">Course Name</label>
                  </div>
                </div>

                <div class="form-group row">

                  <div class="input-field col s3 m2">
                    <input name="group1"  value='Autumn' type="radio" id="autumn" checked="checked" />
                    <label for="autumn">Autumn</label>
                  </div>
                  <div class="input-field col s3 m2">
                    <input name="group1" value='Spring' type="radio" id="spring" />
                    <label for="spring">Spring</label>
                  </div>
                  <div class="input-field col s3 m2">
                    <input name="group1" value='Summer' type="radio" id="summer" />
                    <label for="summer">Summer</label>
                  </div>

                  <div class="col s0 m4">  </div>
                    <div class="input-field col s3 m1">
                      <select  name="year">
                        <option value="2016">2016</option>
                        <option value="2017">2017</option>
                      </select>
                    </div>
                </div>

                <div class = "form-group row">
                  <div class="input-field col s6 m4">
                    <select name="professor" required>
                      {% if professors %}
                      <option value ="" disabled selected >Choose a Professor </option>
                        {% for prof in professors %}
                           <option value = "{{prof.user.username}}">{{prof.user.first_name}} {{prof.user.last_name}}</option>
                        {% endfor %}
                      {% else %}
                        <option value ="" disabled selected>First Hire Some Profs </option>
                      {% endif %}
                    </select>
                  </div>

                  <div class="input-field col s6 m7">
                    <select multiple name="student" required>
                      {% if students %}
                      <option value ="" disabled selected>Choose Whom You Want to Train </option>
                        {% for stud in students %}
                           <option value = "{{stud.user.username}}">{{stud.rollno}}: {{stud.user.first_name}} {{stud.user.last_name}}</option>
                        {% endfor %}
                      {% else %}
                        <option value ="" disabled selected>
                          First Get Some Students
                        </option>
                      {% endif %}
                    </select>
                  </div>
                </div>
                <div>
                  <p style="text-align:center;margin-bottom:10px;color:red;">
                    {{errors}}
                  </p>
                </div>



                <div class="form-group row " style="margin-bottom:0px; margin-top:0px">
                  <div class="input-field col s12 m5">
                    <input name="description1" id="description1" type="text"  value="Midsemester Feedback" required readonly>
                    <label for="description1">Feedback</label>
                  </div>

                  <div class="input-field col s8 m4">
                    <input name="date1" id="date1" type="text" class="datepicker" required>
                    <label for="date1">Last Date for Submission</label>
                  </div>
                  <div class="input-field col s4 m2">
                    <input  name="time1" style="text-align:center" id="time" type="time" class="timepicker" required value="23:59">
                  </div>
                </div>


                <div class="form-group row " style="margin-bottom:0px; margin-top:0px">
                  <div class="input-field col s12 m5">
                    <input name="description2" id="description2" type="text"  value="Endsemester Feedback" required readonly>
                    <label for="description2">Feedback</label>
                  </div>
                  <div class="input-field col s8 m4">
                    <input name="date2" id="date2" type="text" class="datepicker" required>
                    <label for="date2">Last Date for Submission</label>
                  </div>
                  <div class="input-field col s4 m2 ">
                    <input  name="time2" style="text-align:center" id="time" type="time" class="timepicker" required value="23:59">
                  </div>
                </div>



              <div class="form-group row " style="margin-bottom:0px; margin-top:0px">
                <div class="input-field col s12 m5">
                  <input name="description3" id="description3" type="text"  value="Midsemester Examination" required readonly>
                  <label for="description">Deadline</label>
                </div>

                <div class="input-field col s8 m4">
                  <input name="date3" id="date3" type="text" class="datepicker" required>
                  <label for="date3">Date Of Exam</label>
                </div>
                <div class="input-field col s4 m2">
                  <input  name="time3" style="text-align:center" id="time" type="time" class="timepicker" required value="09:30">
                </div>
              </div>


              <div class="form-group row " style="margin-bottom:0px; margin-top:0px">
                <div class="input-field col s12 m5">
                  <input name="description4" id="description4" type="text"  value="Endsemester Examination" required readonly>
                  <label for="description">Deadline</label>
                </div>
                <div class="input-field col s8 m4">
                  <input name="date4" id="date4" type="text" class="datepicker" required>
                  <label for="date4">Date Of Exam</label>
                </div>
                <div class="input-field col s4 m2 ">
                  <input  name="time4" style="text-align:center" id="time" type="time" class="timepicker" required value="09:30">
                </div>
              </div>

              <div class="form-group center" >
                  <button class="btn waves-effect waves-light" type="submit" name="action">Save<i class="material-icons right">send</i>
                  </button>
              </div>

      				</form>
  		      </div>
    	    </div>
  	    </div>
      </div>

    </div>
  </div>
{% endblock %}

{% block script %}
	<script language="JavaScript" src="{% static 'myjs/form1.js' %}"></script>
  <script> $(document).ready(function() { $('select').material_select(); });</script>
  <script language="JavaScript" src="{% static 'myjs/datepick_validate.js' %}"></script>
  <script language="JavaScript" src="{% static 'myjs/choice_add.js' %}"></script>

{% endblock %}

lab10/webServer/webApp/templates/webApp/deadlinesnew.html
{% extends 'webApp/nav.html' %}
{% load staticfiles %}

{% block main1 %}
  <div>
    <div class="row" style="margin-top:2.5em">
      <div class = "col s0 m2"></div>
      <div class = "col s12 m8">
        <div class="card blue-white darken-1">
          <div class="card-content blue-text">
 
            <div class="row">
              <div class="card-title col m3 s0 center">
              </div>
            	<span class="card-title col m6 s12 center">
        				<nav>
        				 	<div class="nav-wrapper" >
        						<ul class="center">
        				    		<li class="active col s12 m12 center">
        				    			<a href="#" style="font-size:1.1em">Add Deadlines</a>
        				    		</li>
        					  	</ul
        				  	</div>
        				</nav>
      		  	</span>
            </div>

            <div>
              <form class="form-horizontal" name="DeadlineForm" action="{% url 'webApp:deadlinesnew' %}" method="post"  autocomplete="off" onsubmit="return valid_check();">{% csrf_token %}

                <div class = "form-group row">
                  <div class="input-field col s6 m3">
                    <select name='course' required>
                      {% if courses %}
                        <option value ="" disabled selected>Choose a Course </option>
                        {% for c in courses %}
                          <option value ="{{c.code}}">{{c.code}}</option>
                        {% endfor %}
                      {% else %}
                        <option value ="" disabled selected>No Courses Added</option>
                      {% endif %}
                    </select>
                  </div>
                </div>

                <div class="form-group row">
                  <div class="input-field col s12 m12">
                    <input name="description" id="description" type="text" class="validate"required>
                    <label for="description">Brief Description</label>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="input-field col s8 m4">
                    <input name="date" id="date" type="text" class="datepicker" required>
                    <label for="date">Submission Date and Time</label>
                  </div>
                  <div class="input-field col s4 m2">

                    <input  name="time" id="time" type="time" class="timepicker"
                    required>

                  </div>
                </div>

                <div class="form-group center" >
                  <button class="btn waves-effect waves-light" type="submit" name="action">Save<i class="material-icons right">send</i>
                  </button>
                </div>
              </form>
            </div>

          </div>
			  </div>
	  	</div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script language="JavaScript" src="{% static 'myjs/datepick_validate.js' %}"></script> 
  <script> $(document).ready(function() { $('select').material_select(); });</script>
{% endblock %}

lab10/webServer/webApp/templates/webApp/home.html
{% extends 'webApp/nav.html' %}
{% block homeURL %}
"#"
{% endblock %}


{% block nav1 %}
class="active"
{% endblock %}

{% block main1 %}
<div style="padding-left:2em;color:green">
    <h5 style="text-transform: capitalize;">Welcome {{user.username}}</h5>
</div>
<div class="row" style="margin-top:2.5em">
    <div class = "col s2 m1">
    </div>
    <div class = "col s8 m4">
        <ul class="collection">
            <li class="collection-item">
                <a href="{% url 'webApp:courses' %}" class="secondary-content" style="float:left"><i class="material-icons"  style="color:blue;">assignment</i></a>
                &emsp;Existing Courses
                <a href="{% url 'webApp:courses' %}" class="secondary-content"><i class="material-icons" >play_arrow</i></a>
            </li>
                <li class="collection-item">
                <a href="{% url 'webApp:deadlines' %}" class="secondary-content" style="float:left"><i class="material-icons" style="color:red;">today</i></a>
                &emsp;Existing Deadlines
                <a href="{% url 'webApp:deadlines' %}" class="secondary-content"><i class="material-icons">play_arrow</i></a>
            </li>
            <li class="collection-item">
                <a href="{% url 'webApp:feedback' %}" class="secondary-content" style="float:left"><i class="material-icons" style="color:green;">assessment</i></a>
                &emsp;Existing Feedback
                <a href="{% url 'webApp:feedback' %}" class="secondary-content"><i class="material-icons">play_arrow</i></a>
            </li>
            <li class="collection-item">
                <a href="{% url 'webApp:coursesnew' %}" class="secondary-content" style="float:left"><i class="material-icons"  style="color:blue;">assignment</i></a>
                &emsp;Add Courses
                <a href="{% url 'webApp:coursesnew' %}" class="secondary-content"><i class="material-icons">play_arrow</i></a>
            </li>
            <!-- <li class="collection-item">
                <a href="{% url 'webApp:deadlinesnew' %}" class="secondary-content" style="float:left"><i class="material-icons" style="color:red;">today</i></a>
                &emsp;Add Deadlines
                <a href="{% url 'webApp:deadlinesnew' %}" class="secondary-content"><i class="material-icons">play_arrow</i></a>
            </li>
            <li class="collection-item">
                <a href="{% url 'webApp:feedbacknew' %}" class="secondary-content" style="float:left"><i class="material-icons" style="color:green;">assessment</i></a>
                &emsp;Add Feedback
                <a href="{% url 'webApp:feedbacknew' %}" class="secondary-content"><i class="material-icons">play_arrow</i></a>
            </li> -->
        </ul>
    </div>
</div>

{% endblock %}

lab10/webServer/webApp/templates/webApp/logout.html
{% extends 'webApp/bkbase.html' %}

{% block main %}
<div style="padding-left:2em;color:green;margin-top:100px">
    <h4 style="text-align:center;text-transform: capitalize;"> {{name}} -   You have successfully logged out !!</h5>
    <h5 style="text-align:right" > Visit again soon !!</h5>
</div>  
{% endblock %}

lab10/webServer/webApp/templates/webApp/nav.html
{% extends 'webApp/bkbase.html' %}
{% block main %}
    <nav class="green">
        <div class="nav-wrapper ">
            <ul id="nav-mobile" class="left">
                <li {% block nav1 %}{% endblock %}><a href={% block homeURL %}"{% url 'webApp:home' %}"{% endblock %}>Home</a></li>
                <li {% block nav2 %}{% endblock %}><a href={% block syncURL %}"{% url 'webApp:studentInitialise' %}"{% endblock %}>Sync Students</a></li>
                <!-- <li {% block nav3 %}{% endblock %}><a href="collapsible.html">JavaScript</a></li> -->
            </ul>
            <a class="brand-logo center"><tab> Feed'er</tab></a>
            <ul id="nav-mobile" class="right">
                <!-- <li {% block nav4 %}{% endblock %}><a href="sass.html">Sass</a></li> -->
                <li {% block nav5 %}{% endblock %}><a href={% block settingsURL %}"{% url 'webApp:settings' %}"{% endblock %}>Change Password</a></li>
                <li ><a href="{% url 'webApp:logout' %}"><i class="material-icons" style="font-size: 22px">power_settings_new</i></a></li>
            </ul>
        </div>
    </nav>
{% block main1 %}
{% endblock %}
{% endblock %}

lab10/webServer/webApp/templates/webApp/signup.html
{% extends 'webApp/base.html' %}

{% block main %}
		<div class="jumbotron">
	 		<div>
	 			<nav class="navbar navbar-default">
				  	<div class="container-fluid" style="padding-right:0px;padding-left:0px;
				  		background-color: #13232e;">
					    <ul style="width:100%" class="nav navbar-nav">
					      <li style="width:50%"><a href="{% url 'webApp:login' %}">Login</a></li>
					      <li style="width:50%" class="active"><a href="#">Sign Up</a></li>
					    </ul>
				 	</div>
				</nav>
				<div style="margin-bottom:20px; font-size:30px; text-align:center;">
					Sign Up, Its Free!!!!
				</div>

				<form class="form-horizontal" name="myForm" action="{% url 'webApp:signup' %}" method="post"  autocomplete="off" onsubmit="return validate_all();">{% csrf_token %}

					<div class="form-group">
			    		<div class="col-sm-10">
			      			<input name="name" id="Text" type="text" class="form-control"  placeholder="Username"
			      			 onkeyup="validate_text();"onkeydown="validate_text();"onblur="validate_text();this.style.borderColor='gray';"
			      			 onfocus="document.querySelector('#ErrText').innerHTML ='';this.style.borderColor='blue';">
			      			<p style="text-align:center; margin-left:15%;" id= "ErrText"></p>
			    		</div>
			  		</div>


					<div class="form-group">
			    		<div class="col-sm-10">
			      			<input type="email" id="Email" class="form-control" name="email" placeholder="Email id"
			      			 onkeyup="validate_email();" onkeydown="validate_email();" onblur="validate_email();this.style.borderColor='gray';"
			      			 onfocus="document.querySelector('#ErrEmail').innerHTML ='';this.style.borderColor='blue';">
			      			<p style="text-align:center; margin-left:15%;" id= "ErrEmail"></p>
			    		</div>
			  		</div>


			  		<div class="form-group">
			    		<div class="col-sm-10">
		      				<input name="pass" id="Pass" type="password" class="form-control"  placeholder="Password" onkeyup="validate_password();" onkeydown="validate_password();" onblur="validate_password();this.style.borderColor='gray';"
		      			 	onfocus="document.querySelector('#ErrPass').innerHTML ='';this.style.borderColor='blue';">
			      			<p style="text-align:center; margin-left:15%;" id= "ErrPass"></p>
			    		</div>
			  		</div>

			  		<div class="form-group">
			    		<div class="col-sm-offset-1 col-sm-12">
			      			<button type="submit" class="btn btn-default">
			      				<b>Register</b>
			      			</button>
			    		</div>
			    	</div>
			  	</form>
			  <div>
		</div>
{% endblock %}