cs251project/django/webServer/webApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'webApp'
urlpatterns = [

    #Admin
    url(r'admin/login/', views.login, name='login'),
	url(r'admin/logout/', views.logout, name='logout'),

    url(r'admin/settings/', views.settings, name='settings'),
    url(r'admin/home/', views.home, name='home'),
    url(r'admin/studentInitialise/', views.studentInitialise, name='studentInitialise'),

    url(r'admin/courses/', views.courses, name='courses'),
	url(r'admin/deadlines/', views.deadlines, name='deadlines'),
    url(r'admin/feedback/', views.feedback, name='feedback'),
    url(r'admin/coursesnew/', views.coursesnew, name='coursesnew'),

    #Instructor
    url(r'deadlinesnew/', views.deadlinesnew, name='ins_deadlinesnew'),
	url(r'feedbacknew/', views.feedbacknew, name='ins_feedbacknew'),
    url(r'deadlinesrunning/', views.deadlines_r, name='deadlines_r'),
    url(r'deadlinesfinished/', views.deadlines_f, name='deadlines_f'),
    url(r'feedback/', views.ins_feedback, name='ins_feedback'),
    url(r'forms/(?P<form_id>[0-9]+)/', views.present_feed, name='present_feed'),
    url(r'forms/question/(?P<ques_id>[0-9]+)/', views.ques_stats, name='ques_stats'),

    url(r'signup/', views.ins_signup, name='ins_signup'),
    url(r'login/', views.ins_login, name='ins_login'),
    url(r'logout/', views.ins_logout, name='ins_logout'),
    url(r'signupsocial/', views.socialsignup, name='socialsignup'),

    url(r'settings/', views.ins_settings, name='ins_settings'),
    url(r'home/', views.ins_home, name='ins_home'),

    #Student
    url(r'api/signin/', views.android_data, name='signin'),
    url(r'api/signout/', views.android_signout, name='signout'),
    url(r'api/feedbacklist/', views.android_feedbacklist, name='feedbackList'),
]

cs251project/django/webServer/webServer/urls.py
from django.conf.urls import include, url
from django.contrib import admin
urlpatterns = [
	url(r'^webApp/', include('webApp.urls')),
    url(r'^admin/', admin.site.urls),
]

cs251project/django/webServer/webApp/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from datetime import date
from datetime import time
import calendar

MaxNameLength = 30;

default_deadlines = {
    'Spring':[date.today().replace(day=28, month=2) ,date.today().replace(day=15, month=4) ],
    'Summer':[date.today().replace(day=1, month=6) ,date.today().replace(day=15, month=7)],
    'Autumn':[date.today().replace(day=6, month=9) ,date.today().replace(day=18, month=11)]
}

class Professor(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return "%s: %s %s" %(self.usernameer.username, self.user.first_name, self.user.last_name)

class Student(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rollno = models.CharField(max_length = 15, primary_key=True)
    token = models.CharField(max_length = 64, default="0")

    def __str__(self):
        return "%s: %s %s" %(self.rollno,self.user.first_name, self.user.last_name)

    class Meta:
        ordering = ('rollno',)

class Course(models.Model):

    code = models.CharField(max_length = 10, primary_key=True)
    name = models.CharField(max_length = 50)
    period = models.CharField(max_length = 20,default='Summer')
    year = models.CharField(max_length = 20,default='2016')

    professor = models.ForeignKey(Professor)
    students = models.ManyToManyField(Student)

    def __str__(self):
        return "%s: %s" %(self.code, self.name)

    class Meta:
        ordering = ('code','name')

class Deadline(models.Model):

    date = models.DateField()
    time = models.TimeField()
    course = models.ForeignKey(Course)
    description = models.TextField(max_length=50)
    isFeedback = models.BooleanField(default=False)

    def __str__(self):
        return "%s" %(self.description)

class FeedbackForm(models.Model):
    deadline = models.ForeignKey(Deadline)
    student = models.ManyToManyField(Student)

class Question(models.Model):
    description = models.TextField(max_length=200)
    feedbackForm = models.ForeignKey(FeedbackForm)

class Response(models.Model):
    question = models.ForeignKey(Question)
    response = models.SmallIntegerField()

cs251project/django/webServer/webApp/views.py
#for basic rendering of html pages
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect

#for authentication login and logout
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required

#models
from django.contrib.auth.models import User
from .models import *

#read student data
import csv
import json

#ins_content
from datetime import date
import datetime
from itertools import chain

#global variables
prof_url='/webApp/login/'
#Admin Settings
def login(request):
	if request.POST :
		user = authenticate(username=request.POST['name'], password=request.POST['pass'])
		if user is not None:
			if user.is_active:
				auth_login(request, user)
				return HttpResponseRedirect('/webApp/admin/home/')
		return render(request, "webApp/admin/login.html",context={'error':'invalid credentials'})
	else:
		if(request.user.is_authenticated):
			return HttpResponseRedirect('/webApp/admin/home/')
		else:
			return render(request, "webApp/admin/login.html",context={'error':''})

@login_required()
def home(request):
	print(request.user.is_superuser)
	if not request.user.is_superuser:
		return HttpResponse("403 Forbidden")
	return render(request, "webApp/admin/home.html")

@login_required()
def logout(request):
	if not request.user.is_superuser:
		return HttpResponse("403 Forbidden")
	data={'name':request.user.username}
	auth_logout(request)
	return render(request, "webApp/admin/logout.html",context=data)

@login_required()
def settings(request):
	if not request.user.is_superuser:
		return HttpResponse("403 Forbidden")
	if request.POST :
		u = User.objects.get(username__exact=request.user.username)
		if not u.check_password(request.POST['currPass']) :
			return render(request, "webApp/admin/settings.html",context={'error':'Current Password Incorrect'})
		else:
			u.set_password(request.POST['newPass'])
		u.save()
		return HttpResponseRedirect('/webApp/admin/logout/')
	else:
		return render(request, "webApp/admin/settings.html",context={'error':''})


#Content pages for Admin
@login_required()
def courses(request):
	if not request.user.is_superuser:
		return HttpResponse("403 Forbidden")
	return render(request, "webApp/admin/courses.html",context={'courses' : Course.objects.all()})

@login_required()
def coursesnew(request):
	if not request.user.is_superuser:
		return HttpResponse("403 Forbidden")
	if request.POST :
		if(len(Course.objects.filter(code=request.POST['code'])) != 0):
			data={
				'professors' : Professor.objects.all(),
				'students' : Student.objects.all(),
				'errors' : 'Course Already Exists'
			}
			return render(request, "webApp/admin/coursesnew.html",context=data)

		profuser = User.objects.get(username=request.POST['professor'])
		prof = Professor.objects.get(user=profuser)

		c = prof.course_set.create(name=request.POST['name'],code=request.POST['code'],
			period=request.POST['group1'],year=request.POST['year'])
		c.save()



		d1 = Deadline(course=c,time=request.POST['time3'],description=request.POST['description3'],
			date=request.POST['date3'])
		d2 = Deadline(course=c,time=request.POST['time4'],description=request.POST['description4'],
			date=request.POST['date4'])
		d1.save()
		d2.save()


		deadl = c.deadline_set.create(time=request.POST['time2'],description=request.POST['description2'],
			date=request.POST['date2'],isFeedback=True)
		deadl.save()
		feedbck = deadl.feedbackform_set.create()
		feedbck.save()

		desc1 = "How good was teaching of instructor?"
		feedbck.question_set.create(description=desc1)
		desc2 = "Percentage of Classes you attended?"
		feedbck.question_set.create(description=desc2)

		deadl1 = c.deadline_set.create(time=request.POST['time1'],description=request.POST['description1'],
			date=request.POST['date1'],isFeedback=True)
		deadl1.save();

		feedbck1 = deadl1.feedbackform_set.create()
		feedbck1.save()

		desc3 = "How good was teaching of instructor?"
		feedbck1.question_set.create(description=desc3)
		desc4 = "Percentage of Classes you attended?"
		feedbck1.question_set.create(description=desc4)


		studusernames = request.POST.getlist('student')
		for i in range(len(studusernames)):
			studuser = User.objects.get(username=studusernames[i])
			stud = Student.objects.get(user=studuser)
			c.students.add(stud)

		return HttpResponseRedirect('/webApp/admin/home/')
	else:
		data={
		'professors' : Professor.objects.all(),
		'students' : Student.objects.all(),
		'errors' : ''
		}
		return render(request, "webApp/admin/coursesnew.html",context=data)

@login_required()
def deadlines(request):
	if not request.user.is_superuser:
		return HttpResponse("403 Forbidden")
	return render(request, "webApp/admin/deadlines.html",context={'deadlines' : Deadline.objects.all()})

@login_required()
def feedback(request):
	if not request.user.is_superuser:
		return HttpResponse("403 Forbidden")
	data={'forms' : [],
	'feedbacks' : []}
	x=FeedbackForm.objects.all()
	data['forms'] = FeedbackForm.objects.all();
	for i in range(len(x)):
		data[i] = Question.objects.filter(feedbackForm=x[i]);
	data['length'] =  len(x);
	return render(request, "webApp/admin/feedback.html",context=data)

#Instructor Settings
def ins_login(request):
	if request.POST :
		usr = User.objects.filter(username=request.POST['username'])
		if len(usr) == 1:
			if usr[0].is_staff and not usr[0].is_superuser:
				user = authenticate(username=request.POST['username'],
					password=request.POST['password'])
				if user is not None:
					if user.is_active:
						auth_login(request, user)
						return HttpResponseRedirect('/webApp/home/')
		return render(request, "webApp/instructor/ins_login.html",
			context={'error':'Invalid Credentials'})
	else:
		print(request.method)
		if(request.user.is_authenticated):
			return HttpResponseRedirect('/webApp/home/')
		else:
			return render(request, "webApp/instructor/ins_login.html",context={'error':''})

def ins_signup(request):
	if request.POST :
		u = User.objects.filter(username=request.POST['username'])
		if len(u) > 0 :
			return render(request, "webApp/instructor/ins_signup.html",
				context={'error':'Username already exits'})

		x= User(username = request.POST['username'],email=request.POST['email'])
		x.set_password(request.POST['password'])
		x.first_name=request.POST['first_name']
		x.last_name=request.POST['last_name']
		x.is_staff=True
		x.save()
		p=Professor(user=x);
		p.save()
		auth_login(request,x)
		return HttpResponseRedirect('/webApp/home/')

	else:
		if(request.user.is_authenticated):
			return HttpResponseRedirect('/webApp/home/')
		else:
			return render(request, "webApp/instructor/ins_signup.html",context={'error':''})

@login_required(login_url=prof_url)
def ins_logout(request):
	if request.user.is_superuser or not request.user.is_staff:
		return HttpResponse("403 Forbidden")
	data={'name':request.user.first_name + " " +request.user.last_name}
	auth_logout(request)
	return render(request, "webApp/instructor/ins_logout.html",context=data)

@login_required(login_url=prof_url)
def ins_settings(request):
	if request.user.is_superuser or not request.user.is_staff:
		return HttpResponse("403 Forbidden")
	if request.POST :
		u = User.objects.get(username__exact=request.user.username)
		if not u.check_password(request.POST['currPass']) :
			return render(request, "webApp/instructor/ins_settings.html",context={'error':'Current Password Incorrect'})
		else:
			u.set_password(request.POST['newPass'])
		u.save()
		return HttpResponseRedirect('/webApp/logout/')
	else:
		return render(request, "webApp/instructor/ins_settings.html",context={'error':''})

@login_required(login_url=prof_url)
def ins_home(request):
	if request.user.is_superuser or not request.user.is_staff:
		return HttpResponse("403 Forbidden")
	return render(request, "webApp/instructor/ins_home.html")


#Content pages for Instructor
@login_required(login_url=prof_url)
def deadlinesnew(request):
	if request.user.is_superuser or not request.user.is_staff:
		return HttpResponse("403 Forbidden")
	if request.POST :
		corse = Course.objects.filter(code=request.POST['course'])
		deadl = corse[0].deadline_set.create(date=request.POST['date'],time=request.POST['time'],description=request.POST['description'])
		deadl.save()

		return HttpResponseRedirect('/webApp/home/')
	else:
		return render(request, "webApp/instructor/deadlinesnew.html",context={'courses' : Course.objects.all()})

@login_required(login_url=prof_url)
def ins_feedback(request):
	if request.user.is_superuser or not request.user.is_staff:
		return HttpResponse("403 Forbidden")
	return render(request, "webApp/instructor/feedback.html",context={'forms':FeedbackForm.objects.all()})

@login_required(login_url=prof_url)
def present_feed(request,form_id):
	if request.user.is_superuser or not request.user.is_staff:
		return HttpResponse("403 Forbidden")
	feed = FeedbackForm.objects.get(id=form_id)

	total_students = len(Student.objects.filter(course=feed.deadline.course))
	questions = Question.objects.filter(feedbackForm=feed)
	detail={}
	total_responses = 0
	for q in questions:
		detail[q.id]=Response.objects.filter(question=q)
	if len(questions) > 0:
		total_responses = len(Response.objects.filter(question=questions[0]))
	return render(request,"webApp/instructor/detailedfeed.html",context={
		'detail':detail,
		'questions':questions,
		'form':feed,
		'total_students':total_students,
		'total_responses':len(list(range(total_responses))),
		'count_responses':list(range(total_responses))
	})

@login_required(login_url=prof_url)
def ques_stats(request,ques_id):
	if request.user.is_superuser or not request.user.is_staff:
		return HttpResponse("403 Forbidden")
	ques = Question.objects.get(id=ques_id)
	res = Response.objects.filter(question=ques)
	return render(request,"webApp/instructor/question_stats.html",context={

cs251project/django/webServer/webApp/templates/webApp/instructor/deadlinesnew.html
{% extends 'webApp/ins_nav.html' %}
{% load staticfiles %}

{% block main1 %}
  <div>
    <div class="row" style="margin-top:2.5em">
      <div class = "col s0 m2"></div>
      <div class = "col s12 m8">
        <div class="card blue-white darken-1">
          <div class="card-content blue-text">
 
            <div class="row">
              <div class="card-title col m3 s0 center">
              </div>
            	<span class="card-title col m6 s12 center">
        				<nav>
        				 	<div class="nav-wrapper" >
        						<ul class="center">
        				    		<li class="active col s12 m12 center">
        				    			<a href="#" style="font-size:1.1em">Add Deadlines</a>
        				    		</li>
        					  	</ul
        				  	</div>
        				</nav>
      		  	</span>
            </div>

            <div>
              <form class="form-horizontal" name="DeadlineForm" action="{% url 'webApp:ins_deadlinesnew' %}" method="post"  autocomplete="off" onsubmit="return valid_check();">{% csrf_token %}

                <div class = "form-group row">
                  <div class="input-field col s6 m3">
                    <select name='course' required>
                      {% if courses %}
                        <option value ="" disabled selected>Choose a Course </option>
                        {% for c in courses %}
                          <option value ="{{c.code}}">{{c.code}}</option>
                        {% endfor %}
                      {% else %}
                        <option value ="" disabled selected>No Courses Added</option>
                      {% endif %}
                    </select>
                  </div>
                </div>

                <div class="form-group row">
                  <div class="input-field col s12 m12">
                    <input name="description" id="description" type="text" class="validate"required>
                    <label for="description">Brief Description</label>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="input-field col s8 m4">
                    <input name="date" id="date" type="text" class="datepicker" required>
                    <label for="date">Submission Date and Time</label>
                  </div>
                  <div class="input-field col s4 m2">

                    <input  name="time" id="time" type="time" class="timepicker"
                    required>

                  </div>
                </div>

                <div class="form-group center" >
                  <button class="btn waves-effect waves-light" type="submit" name="action">Save<i class="material-icons right">send</i>
                  </button>
                </div>
              </form>
            </div>

          </div>
			  </div>
	  	</div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script language="JavaScript" src="{% static 'myjs/datepick_validate.js' %}"></script> 
  <script> $(document).ready(function() { $('select').material_select(); });</script>
{% endblock %}

cs251project/django/webServer/webApp/templates/webApp/instructor/detailedfeed.html
{% extends 'webApp/ins_nav.html' %}
{% load staticfiles %}
{% block main1 %}
  <div>
    <div class="row" style="margin-top:2.5em">
      <div class = "col s0 m1"></div>
      <div class = "col s12 m10">
        <div class="card blue-white darken-1">
          <div class="card-content blue-text">

            <div class="row">
              <div class="card-title col m3 s0 center">
              </div>

              <span class="card-title col m6 s12 center">
        				<nav>
        				 	<div class="nav-wrapper">
        						<ul class="center">
        				    		<li class="active col s12 m12 center">
        				    			<a class="flow-text tooltipped" data-position="top" data-delay="50" data-tooltip="{{total_responses}}/{{total_students}}"
                          style="font-size:1.1em">{{form.deadline.course.code}} - {{form.deadline.description}}</a>
        				    		</li>
        					  	</ul
        				  	</div>
        				</nav>
      		  	</span>
            </div>

            <div class="row">
            <div class = "col s12 m12">
              {% if questions %}
                <table class="highlight bordered" style="color:darkblue">
                    {% for q in questions %}
                    <tr> 
                      <th><a href="{% url 'webApp:ques_stats' ques_id=q.id%}"
                      class="flow-text tooltipped" data-position="top" data-delay="50" data-tooltip="{{q.description}}">
                      Q{{forloop.counter}}</a></th>
                      {% for c in q.response_set.all %}
                         <td >{{c.response}}</td>
                      {% endfor %}
                    </tr>
                    {% endfor %}
                 <tbody>
                </table>
              {% else %}
                <p style="text-align:center;font-size:2em;color:darkblue;">No Responses yet</p>
              {% endif %}
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
    $(document).ready(function(){
    $('.tooltipped').tooltip({delay: 50});
    });
  </script>
{% endblock %}

cs251project/django/webServer/webApp/templates/webApp/instructor/ins_home.html
{% extends 'webApp/ins_nav.html' %}
{% block homeURL %}
"#"
{% endblock %}


{% block nav1 %}
class="active"
{% endblock %}

{% block main1 %}
<div style="padding-left:2em;color:green">
    <h5 style="text-transform: capitalize; text-align:center">Welcome {{user.first_name}} {{user.last_name}}</h5>
</div>
<div class="row" style="margin-top:2.5em">
    <div class = "col s2 m1">
    </div>
    <div class = "col s8 m4">
        <ul class="collection">
            <li class="collection-item">
                <a href="{% url 'webApp:deadlines_f' %}" class="secondary-content" style="float:left"><i class="material-icons" style="color:red;">today</i></a>
                &emsp;Existing Deadlines
                <a href="{% url 'webApp:deadlines_f' %}" class="secondary-content"><i class="material-icons">play_arrow</i></a>
            </li>
            <li class="collection-item">
                <a href="url 'webApp:ins_feedback' %}" class="secondary-content" style="float:left"><i class="material-icons" style="color:green;">assessment</i></a>
                &emsp;Existing Feedback
                <a href="{% url 'webApp:ins_feedback' %}" class="secondary-content"><i class="material-icons">play_arrow</i></a>
            </li>
            <li class="collection-item">
                <a href="{% url 'webApp:ins_deadlinesnew' %}" class="secondary-content" style="float:left"><i class="material-icons" style="color:red;">today</i></a>
                &emsp;Add Deadlines
                <a href="{% url 'webApp:ins_deadlinesnew' %}" class="secondary-content"><i class="material-icons">play_arrow</i></a>
            </li>
            <li class="collection-item">
                <a href="{% url 'webApp:ins_feedbacknew' %}" class="secondary-content" style="float:left"><i class="material-icons" style="color:green;">assessment</i></a>
                &emsp;Add Feedback
                <a href="{% url 'webApp:ins_feedbacknew' %}" class="secondary-content"><i class="material-icons">play_arrow</i></a>
            </li>
        </ul>
    </div>
</div>

{% endblock %}

cs251project/django/webServer/webApp/templates/webApp/instructor/ins_login.html
{% extends 'webApp/bkbase.html' %}

{% load staticfiles %}
{% block main %}
	<script>
	 	function FBlogin(response) {
		  	FB.login(function(response){
			  	if (response.status === 'connected') {
			    	// Logged into your app and Facebook.
			    	console.log(response);
			    	testAPI();
			  	} else if (response.status === 'not_authorized') {
			    	// The person is logged into Facebook, but not your app.
			    	document.getElementById('status').innerHTML = 'Please log into this app.';
			  	} else {
			    	// The person is not logged into Facebook, so we're not sure if
			    	// they are logged into this app or not.
			    	document.getElementById('status').innerHTML = 'Please log into Facebook.';
			  	}
			}, {scope:'public_profile,email'});
		}
	 	function checkLoginState() {
		    FB.getLoginStatus(function(response) {
	    		FBlogin(response);
	    	});
  		}
		window.fbAsyncInit = function() {
		  	FB.init({
			    appId      : '1797499347130875',
			    cookie     : true,  // enable cookies to allow the server to access	 the session
			    xfbml      : true,  // parse social plugins on this page
			   	oauth      : true,
			    version    : 'v2.8' // use graph api version 2.5
		  	});
		};

  		// Load the SDK asynchronously
		(function(d, s, id) {
		    var js, fjs = d.getElementsByTagName(s)[0];
		    if (d.getElementById(id)) return;
		    js = d.createElement(s); js.id = id;
		    js.src = "//connect.facebook.net/en_US/sdk.js";
		    fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));

		function post(path, params) {
		    var form = document.createElement("form");
		    form.setAttribute("method", 'post');
		    form.setAttribute("action", path);

		    for(var key in params) {
		        if(params.hasOwnProperty(key)) {
		            var hiddenField = document.createElement("input");
		            hiddenField.setAttribute("type", "hidden");
		            hiddenField.setAttribute("name", key);
		            hiddenField.setAttribute("value", params[key]);
		            form.appendChild(hiddenField);
		         }
		    }
		    document.body.appendChild(form);
		    form.submit();
		}

	  	function testAPI() {
		    console.log('Welcome!  Fetching your information.... ');
		    FB.api('/me?locale=en_US&fields=name,email,first_name,last_name', function(response) {
		      	console.log('Successful login for: ' + response.name);
		      	document.getElementById('status').innerHTML =
		      		'Thanks for logging in,' + response.name + '!';
		        console.log(response);
		        var a="{% csrf_token %}"
		     
		        post('/webApp/signupsocial/',
		        	{
		        		'id': response.id,	
		        		'name': response.name,
		        		'email': response.email,
		        		'first_name': response.first_name,
		        		'last_name': response.last_name,
		        		'csrfmiddlewaretoken':a.substring(55,119)
		    		});
		    	
		    });
		}
	</script>

	<div class="row">
		<div class = "col m4 s1 center">
		</div>

		<div class = "col m4 s10">
		  <div class="row" style=" margin-top:7em">
		    <div>
		      <div class="card blue-grey darken-1">
		        <div class="card-content white-text">

		          	<span class="card-title">
						<nav style="margin-bottom: 1em;">
						 	<div class="nav-wrapper" >
								<ul class="center">
						    		<li class="active col s12 m6 center" style="padding-left:0px;padding-right:0px;">
						    			<a href="#" style="font-size:1em">Login</a>
						    		</li>
						    		<li class="col s12 m6 center" style="padding-left:0px;padding-right:0px;">
						    			<a href="{% url 'webApp:ins_signup' %}" style="font-size:1em">Signup</a>
						    		</li>
							  	</ul
						  	</div>
						</nav>
				  	</span>

			  		<div>
			  			<form action="{% url 'webApp:ins_login' %}" method="post"  autocomplete="off">{% csrf_token %}
			  				
			  				<div class="row">
								<div class="input-field col m12 s12">
							  		<i class="material-icons prefix">lock</i>
							  		<input name="username"id="username" type="text" class="validate" required>
							  		<label for="icon_prefix">Username</label>
								</div>
								<div class="input-field col m12 s12">
							  		<i class="material-icons prefix">vpn_key</i>
							  		<input name="password"id="password" type="password" class="validate" required>
							  		<label for="icon_prefix">Password</label>
								</div>
							</div>

							<div id="status"style="text-align:center;margin-bottom:20px">
								{% block error %}
				  			    	{{error}}
				  			    {% endblock %}
				  		   	</div>

							<div class="form-group center" >
								<button class="btn waves-effect waves-light" type="submit" name="action">Login<i class="material-icons right">send</i>
								</button>
					  	    </div>
					  	    
		  				</form>

		  				<div class="row" style="padding-top:0.5rem">
					  	    <div class="form-group center">
					  	    	<button class="btn btn-default fb-btn" onclick="checkLoginState();">Sign in through Facebook
					  	   		</button>
	    					</div> 
	    				</div>
					</div>
			  	</div>
			  </div>
		    </div>
		  </div>
		</div>
	</div>
{% endblock %}

cs251project/django/webServer/webApp/templates/webApp/instructor/ins_logout.html
{% extends 'webApp/bkbase.html' %}

{% block main %}
<div style="padding-left:2em;color:green;margin-top:100px">
    <h4 style="text-align:center;text-transform: capitalize;"> {{name}} -   You have successfully logged out !!</h5>
    <h5 style="text-align:right" > Visit again soon !!</h5>
</div>  
{% endblock %}

cs251project/django/webServer/webApp/templates/webApp/instructor/ins_signup.html
{% extends 'webApp/bkbase.html' %}

{% block main %}
	<div class="row">
		<div class = "col m4 s1 center">
		</div>
		<div class = "col m4 s10">
		  	<div class="row" style=" margin-top:7em">
	      		<div class="card blue-grey darken-1">
	        		<div class="card-content white-text">
			          	<span class="card-title">
							<nav style="margin-bottom: 1em;">
							 	<div class="nav-wrapper" >
									<ul class="center">
										<li class="col s6 m6 center" style="padding-left:0px;padding-right:0px;">
							    			<a href="{% url 'webApp:ins_login' %}" style="font-size:1em">Login</a>
							    		</li>
										<li class="active col s6 m6 center" style="padding-left:0px;padding-right:0px;">
								    		<a href="#" style="font-size:1em">Signup</a>
							    		</li>
								  	</ul
							  	</div>
							</nav>
					  	</span>

				  		<div>
				  			<form action="{% url 'webApp:ins_signup' %}" method="post"  autocomplete="off" >{% csrf_token %}
				  				
							  	<div class="row">
									<div class="input-field col s12 m6">
								  		<i class="material-icons prefix">account_circle</i>
								  		<input name="first_name" id="first_name" type="text" class="validate" required>
								  		<label for="icon_prefix">First Name</label>
									</div>
									<div class="input-field col s12 m6">
									<i class="material-icons prefix mobile">account_circle</i>
										<input name="last_name" id="last_name" type="text" class="validate">
								  		<label for="icon_telephone">Last Name</label>
									</div>
									<div class="input-field col m12 s12">
								  		<i class="material-icons prefix">lock</i>
								  		<input name="username"id="username" type="text" class="validate" required>
								  		<label for="icon_prefix">Username</label>
									</div>
									<div class="input-field col m12 s12">
								  		<i class="material-icons prefix">email</i>
								  		<input name="email"id="email" type="email" class="validate" required>
								  		<label for="icon_prefix">Email Id</label>
									</div>
									<div class="input-field col m12 s12">
								  		<i class="material-icons prefix">vpn_key</i>
								  		<input name="password"id="password" type="password" class="validate" required>
								  		<label for="icon_prefix">Password</label>
									</div>
								</div>

								<div id="status"style="text-align:center;margin-bottom:20px">
									{% block error %}
					  			    	{{error}}
					  			    {% endblock %}
					  		   	</div>

								<div class="form-group center" >
									<button class="btn waves-effect waves-light" type="submit" name="action">SignUp<i class="material-icons right">send</i>
									</button>
						  	    </div>

			  				</form>
						</div>
		  			</div>
		  		</div>
		  	</div>
		</div>
	</div>
{% endblock %}